filter:
  paths:
    - 'src/*'
checks:
  php:
    code_rating: true
    variable_existence: true
    useless_calls: true
    use_statement_alias_conflict: true
    unused_variables: true
    unused_properties: true
    unused_parameters: true
    unused_methods: true
    unreachable_code: true
    security_vulnerabilities: true
    parameter_non_unique: true
    no_non_implemented_abstract_methods: true
    deprecated_code_usage: true
    closure_use_not_conflicting: true
    closure_use_modifiable: true
    avoid_conflicting_incrementers: true
    assignment_of_null_return: true
    verify_argument_usable_as_reference: true
    verify_access_scope_valid: true
    verify_property_names: true
    uppercase_constants: true
    too_many_arguments: true
    spacing_of_function_arguments: true
    spacing_around_non_conditional_operators: true
    spacing_around_conditional_operators: true
    space_after_cast: true
    single_namespace_per_use: true
    side_effects_or_types: true
    return_doc_comments: true
    return_doc_comment_if_not_inferrable: true
    require_scope_for_properties: true
    require_scope_for_methods: true
    require_php_tag_first: true
    require_braces_around_control_structures: true
    remove_trailing_whitespace: true
    remove_php_closing_tag: true
    remove_extra_empty_lines: true
    psr2_control_structure_declaration: true
    psr2_class_declaration: true
    property_assignments: true
    properties_in_camelcaps: true
    prefer_while_loop_over_for_loop: true
    prefer_unix_line_ending: true
    php5_style_constructor: true
    parameters_in_camelcaps: true
    parameter_doc_comments: true
    param_doc_comment_if_not_inferrable: true
    optional_parameters_at_the_end: true
    one_class_per_file: true
    non_commented_empty_catch_block: true
    no_unnecessary_if: true
    no_unnecessary_function_call_in_for_loop: true
    no_underscore_prefix_in_properties: true
    no_underscore_prefix_in_methods: true
    no_new_line_at_end_of_file: true
    no_global_keyword: true
    no_exit: true
    no_eval: true
    no_else_if_statements: true
    no_debug_code: true
    no_commented_out_code: true
    more_specific_types_in_doc_comments: true
    missing_arguments: true
    method_calls_on_non_object: true
    lowercase_basic_constants: true
    function_in_camel_caps: true
    function_body_start_on_new_line: true
    foreach_usable_as_reference: true
    foreach_traversable: true
    fix_use_statements:
      remove_unused: true
      preserve_multiple: false
      preserve_blanklines: false
      order_alphabetically: true
    fix_linefeed: true
    fix_doc_comments: true
    ensure_lower_case_builtin_functions: true
    deadlock_detection_in_loops: true
    classes_in_camel_caps: true
    catch_class_exists: true
    avoid_unnecessary_concatenation: true
    avoid_space_indentation: true
    avoid_multiple_statements_on_same_line: true
    avoid_corrupting_byteorder_marks: true
    avoid_closing_tag: true
    avoid_aliased_php_functions: true
    argument_type_checks: true
    simplify_boolean_return: true

tools:
  external_code_coverage: true