sudo: false
language: php
php:
  - 7.1
  - 5.6
  - 5.4
matrix:
  fast_finish: true
before_script:
  - ./scripts/travis/setup.sh
  - php -i
script:
  - ./scripts/travis/run-tests.sh
after_script:
  - ./scripts/travis/uploadCodeCoverage.sh