language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - hhvm
matrix:
  fast_finish: true
before_script:
  - ./scripts/travis/setup.sh
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then php -i; fi"
script:
  - ./scripts/travis/run-tests.sh
after_script:
  - ./scripts/travis/uploadCodeCoverage.sh