sudo: false
language: php
php:
  - 7.0
  - 7.1
  - nightly
matrix:
  fast_finish: true
before_script:
  - ./scripts/travis/setup.sh
script:
  - ./scripts/travis/run-tests.sh
after_script:
  - ./scripts/travis/uploadCodeCoverage.sh